name: Flutter APK Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Забираємо код репозиторію
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Встановлюємо Flutter конкретної версії
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.10'  # конкретна стабільна версія

      # 3. Встановлюємо залежності
      - name: Install dependencies
        run: flutter pub get

      # 4. Будуємо debug APK
      - name: Build APK
        run: flutter build apk --debug

      # 5. Завантажуємо APK як артефакт
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk


